services:
  - type: web
    name: biosearch
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "true"
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: biosearch-data
      mountPath: /data
      sizeGB: 1 