services:
  - type: web
    name: biosearch
    env: python
    buildCommand: |
      pip install -r requirements.txt
      # Ensure static directories exist and have proper permissions
      mkdir -p static/js
      mkdir -p static/css
      mkdir -p static/img
      chmod -R 755 static
    startCommand: gunicorn wsgi:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: RENDER_EXTERNAL_URL
        sync: false
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: biosearch-data
      mountPath: /data
      sizeGB: 1 